# Generated by Django 2.1.4 on 2018-12-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_website_user',
            new_name='is_user',
        ),
    ]
