# Generated by Django 2.1.4 on 2018-12-16 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181215_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
