# Generated by Django 2.1.4 on 2018-12-16 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
