# Generated by Django 2.1.4 on 2018-12-18 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expense_date', models.DateField()),
                ('cost_name', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_cost_user',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'extra_cost',
                'verbose_name_plural': 'extra_costs',
                'db_table': 'extra_costs',
            },
        ),
    ]
