# Generated by Django 2.1.4 on 2018-12-16 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meal_date', models.DateField()),
                ('item_name', models.CharField(max_length=255)),
                ('item_weight', models.FloatField(blank=True, null=True)),
                ('item_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazaar_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bazaar',
                'verbose_name_plural': 'bazaar',
                'db_table': 'bazaar',
            },
        ),
    ]
