# Generated by Django 2.1.4 on 2018-12-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_date',
            new_name='bazaar_date',
        ),
    ]
